replicaCount: 2

image:
  repository: art222324/devops-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  nodePort: 30080

ingress:
  enabled: false
  host: devops-app.local
  annotations: {}

resources: {}

autoscaling:
  enabled: false

