replicaCount: 2

image:
  repository: art222324/devops-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000
  # nodePort: 30123   # opcional; comente se quiser que o Kubernetes escolha automaticamente

ingress:
  enabled: false
  host: devops-app.local
  annotations: {}

resources: {}

autoscaling:
  enabled: false
