name: CI/CD Pipeline - DevOps App

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar ambiente Python
      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Instalar dependências e rodar testes
      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: pytest -v

      # 4. Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build e Push da imagem Docker
      - name: Build e Push da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.run_number }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # 1. Clonar o repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar kubectl
      - name: Configurar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'

      # 3. Configurar Helm
      - name: Configurar Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      # 4. Configurar acesso ao cluster
      - name: Configurar acesso ao cluster
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      # 5. Deploy via Helm
      - name: Deploy via Helm
        run: |
          helm upgrade --install devops-app ./helm/devops-app \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/devops-app \
            --set image.tag=latest
